load(
    "@rules_cc//cc:defs.bzl",
    "cc_binary",
)

cc_binary(
    name = "abstract_factory",
    srcs = ["abstract_factory.cpp"],
)

cc_binary(
    name = "builder",
    srcs = ["builder.cpp"],
)

cc_binary(
    name = "visitor",
    srcs = ["visitor.cpp"],
)
