LEVEL_3_PLATFORM = "x86"

_BUILD_DEFINE_BASE = "NM_CORE_TYPES_X86_IMPLEMENTATION"
BUILD_DEFINE_GENERAL = "%s=1" % _BUILD_DEFINE_BASE
BUILD_DEFINE_MMX = "%s=2" % _BUILD_DEFINE_BASE
BUILD_DEFINE_SSE_1 = "%s=3" % _BUILD_DEFINE_BASE
BUILD_DEFINE_SSE_2 = "%s=4" % _BUILD_DEFINE_BASE
BUILD_DEFINE_SSE_3 = "%s=5" % _BUILD_DEFINE_BASE
BUILD_DEFINE_SSSE_3 = "%s=6" % _BUILD_DEFINE_BASE
BUILD_DEFINE_SSE_4_1 = "%s=7" % _BUILD_DEFINE_BASE
BUILD_DEFINE_SSE_4_2 = "%s=8" % _BUILD_DEFINE_BASE
BUILD_DEFINE_AVX_1 = "%s=9" % _BUILD_DEFINE_BASE
BUILD_DEFINE_AVX_2 = "%s=10" % _BUILD_DEFINE_BASE
BUILD_DEFINE_AVX_512 = "%s=11" % _BUILD_DEFINE_BASE
