cc_binary(
    name = "abstract_factory",
    srcs = ["abstract_factory.cpp"],
)

cc_binary(
    name = "builder",
    srcs = ["builder.cpp"],
)

cc_binary(
    name = "visitor",
    srcs = ["visitor.cpp"],
)

cc_binary(
    name = "flood",
    srcs = ["flood.cpp"],
)

cc_binary(
    name = "command_buffer",
    srcs = ["command_buffer.cpp"],
)

cc_binary(
    name = "icd_plain",
    srcs = ["icd_plain.cpp"],
)

cc_binary(
    name = "icd_extra",
    srcs = ["icd_extra.cpp"],
)

cc_binary(
    name = "icd_vk",
    srcs = ["icd_vk.cpp"],
    deps = ["@com_github_google_benchmark//:benchmark_main"],
)

cc_binary(
    name = "memory",
    srcs = ["memory.cpp"],
)

cc_binary(
    name = "bench",
    srcs = ["bench.cpp"],
    deps = ["@com_github_google_benchmark//:benchmark_main"],
)
