load("//randoms/foundation/frameworks/core/simd/common/general:build_defines.bzl", _LEVEL_3_IMPLEMENTATION_GENERAL = "LEVEL_3_IMPLEMENTATION")

LEVEL_3_PLATFORM = "common"

IMPLEMENTATION_DEFAULT = _LEVEL_3_IMPLEMENTATION_GENERAL

_BUILD_DEFINE_BASE = "NM_CORE_SIMD_COMMON_IMPLEMENTATION"
BUILD_DEFINE_GENERAL = "%s=1" % _BUILD_DEFINE_BASE
